### ISSUE TITLE
How to use unadversarial patches in the testing stage?

### ISSUE THREAD

**Issue by wqfdewifi** [microsoft/unadversarial#1]
Thank you for your amazing work. 

Could you please tell me how to add patches to each sample during the testing stage? I have read the code and it seems like the ground-truth is needed to help each sample add the corresponding category of patches during testing.  I wonder if this is fair. Or maybe I made mistake…… 
![image](https://user-images.githubusercontent.com/54132689/145069057-edc69859-dfd1-4f57-8c83-84f9373eac7b.png)

Looking forward to your reply! Thanks a lot.

**Comment by Hadisalman** [comment]
Hi @wqfdewifi!

Indeed the ground truth is needed to add the unadversarial patch. In this work, we assume that we have control over the objects of interest that we would like to recognize, which shows up in many scenarios in the real world (See Section 2 of [our paper](https://arxiv.org/pdf/2012.12235.pdf)). To concretize things, when placing an unadversarial patch on some object (e.g. a cup), we already know the class of that object. Yet we place the unadversarial patch on the object to robustly recognize it in the future. 

To simulate this on standard datasets such as ImageNet or CIFAR-10, we simply assume we know the ground truth of the image, and place the unadversarial patch on random location in the image. Then we test the performance of classifiers under various distribution shifts.

Hope this clarifies things!

**Comment by wqfdewifi** [comment]
Thank you for your answer. I'm clear now! : )
